---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-reader

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-reader
rules:
- apiGroups: [""]
  resources: ["namespaces","replicasets"] 
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-reader
subjects:
- kind: ServiceAccount
  name: image-reader
  namespace: default
roleRef:
  kind: ClusterRole
  name: image-reader
  apiGroup: rbac.authorization.k8s.io
